### ISSUE TITLE
grub2-mkconfig not creating submenu on RHEL(

### ISSUE THREAD

**Issue by nixfu** [snapshotmanager/boom#27]
All my snapshot entries are showing up as regular grub items.

I have this in /etc/default/boom:
BOOM_USE_SUBMENU="yes"
BOOM_SUBMENU_NAME="Snapshots"

And this in /etc/default/grub:
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=false
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="pci=nommconf,bfsort crashkernel=0M-4G:168M,4G-256G:256M,256G-:512M rhgb quiet rd.shell=0 ipv6.disable=1 rd.plymouth=0 rd.lvm.vg=rootvg rd.lvm.lv=rootvg/lv_root rd.lvm.lv=rootvg/lv_swap"
GRUB_DISABLE_RECOVERY=true
GRUB_DISABLE_OS_PROBER=true
GRUB_ENABLE_BLSCFG=true

But still no grub submenu is ever created, just entries in the list.

**Comment by bmr-cymru** [comment]
What distribution are you using? The Snapshots submenu is only supported on RHEL7 and earlier due to changes in the distribution: on RHEL8 and later, as well as Fedora 30 onwards the BootLoader Specification is used by default, which means that the boom-managed boot entries cannot be placed in a separate submenu. Later releases of boom have removed the configuration options, but they are still present in older distribution packages on RHEL8.
